# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protogen.coresrv_pb2 as coresrv__pb2


class CoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/coresrv.CoreService/Ping',
                request_serializer=coresrv__pb2.PingRequest.SerializeToString,
                response_deserializer=coresrv__pb2.PingReply.FromString,
                )
        self.BulkStoreGameSales = channel.unary_unary(
                '/coresrv.CoreService/BulkStoreGameSales',
                request_serializer=coresrv__pb2.BulkStoreGameSalesRequest.SerializeToString,
                response_deserializer=coresrv__pb2.BulkStoreGameSalesReply.FromString,
                )
        self.GetGameSalesByRank = channel.unary_unary(
                '/coresrv.CoreService/GetGameSalesByRank',
                request_serializer=coresrv__pb2.GetGameSalesByRankRequest.SerializeToString,
                response_deserializer=coresrv__pb2.GetGameSalesByRankReply.FromString,
                )
        self.SearchGameSalesByName = channel.unary_unary(
                '/coresrv.CoreService/SearchGameSalesByName',
                request_serializer=coresrv__pb2.SearchGameSalesByNameRequest.SerializeToString,
                response_deserializer=coresrv__pb2.SearchGameSalesByNameReply.FromString,
                )
        self.GetTopNGamesOfPlatforms = channel.unary_unary(
                '/coresrv.CoreService/GetTopNGamesOfPlatforms',
                request_serializer=coresrv__pb2.GetTopNGamesOfPlatformsRequest.SerializeToString,
                response_deserializer=coresrv__pb2.GetTopNGamesOfPlatformsReply.FromString,
                )
        self.GetTopNGamesOfYear = channel.unary_unary(
                '/coresrv.CoreService/GetTopNGamesOfYear',
                request_serializer=coresrv__pb2.GetTopNGamesOfYearRequest.SerializeToString,
                response_deserializer=coresrv__pb2.GetTopNGamesOfYearReply.FromString,
                )
        self.GetTopNGamesOfGenre = channel.unary_unary(
                '/coresrv.CoreService/GetTopNGamesOfGenre',
                request_serializer=coresrv__pb2.GetTopNGamesOfGenreRequest.SerializeToString,
                response_deserializer=coresrv__pb2.GetTopNGamesOfGenreReply.FromString,
                )
        self.Get5MostSoldGamesByYearAndPlatform = channel.unary_unary(
                '/coresrv.CoreService/Get5MostSoldGamesByYearAndPlatform',
                request_serializer=coresrv__pb2.Get5MostSoldGamesByYearAndPlatformRequest.SerializeToString,
                response_deserializer=coresrv__pb2.Get5MostSoldGamesByYearAndPlatformReply.FromString,
                )
        self.GetGameSalesWithMoreSalesInEUThanNA = channel.unary_unary(
                '/coresrv.CoreService/GetGameSalesWithMoreSalesInEUThanNA',
                request_serializer=coresrv__pb2.GetGameSalesWithMoreSalesInEUThanNARequest.SerializeToString,
                response_deserializer=coresrv__pb2.GetGameSalesWithMoreSalesInEUThanNAReply.FromString,
                )
        self.GetGameSalesInIds = channel.unary_unary(
                '/coresrv.CoreService/GetGameSalesInIds',
                request_serializer=coresrv__pb2.GetGameSalesInIdsRequest.SerializeToString,
                response_deserializer=coresrv__pb2.GetGameSalesInIdsReply.FromString,
                )
        self.GetYearlyTotalGameSalesInRange = channel.unary_unary(
                '/coresrv.CoreService/GetYearlyTotalGameSalesInRange',
                request_serializer=coresrv__pb2.GetYearlyTotalGameSalesInRangeRequest.SerializeToString,
                response_deserializer=coresrv__pb2.GetYearlyTotalGameSalesInRangeReply.FromString,
                )
        self.GetTotalPublishersGameSalesInYearsRange = channel.unary_unary(
                '/coresrv.CoreService/GetTotalPublishersGameSalesInYearsRange',
                request_serializer=coresrv__pb2.GetTotalPublishersGameSalesInYearsRangeRequest.SerializeToString,
                response_deserializer=coresrv__pb2.GetTotalPublishersGameSalesInYearsRangeReply.FromString,
                )
        self.GetTotalGameSalesInYearsRangeByGenre = channel.unary_unary(
                '/coresrv.CoreService/GetTotalGameSalesInYearsRangeByGenre',
                request_serializer=coresrv__pb2.GetTotalGameSalesInYearsRangeByGenreRequest.SerializeToString,
                response_deserializer=coresrv__pb2.GetTotalGameSalesInYearsRangeByGenreReply.FromString,
                )


class CoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkStoreGameSales(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGameSalesByRank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchGameSalesByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopNGamesOfPlatforms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopNGamesOfYear(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopNGamesOfGenre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get5MostSoldGamesByYearAndPlatform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGameSalesWithMoreSalesInEUThanNA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGameSalesInIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetYearlyTotalGameSalesInRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotalPublishersGameSalesInYearsRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotalGameSalesInYearsRangeByGenre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=coresrv__pb2.PingRequest.FromString,
                    response_serializer=coresrv__pb2.PingReply.SerializeToString,
            ),
            'BulkStoreGameSales': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkStoreGameSales,
                    request_deserializer=coresrv__pb2.BulkStoreGameSalesRequest.FromString,
                    response_serializer=coresrv__pb2.BulkStoreGameSalesReply.SerializeToString,
            ),
            'GetGameSalesByRank': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameSalesByRank,
                    request_deserializer=coresrv__pb2.GetGameSalesByRankRequest.FromString,
                    response_serializer=coresrv__pb2.GetGameSalesByRankReply.SerializeToString,
            ),
            'SearchGameSalesByName': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchGameSalesByName,
                    request_deserializer=coresrv__pb2.SearchGameSalesByNameRequest.FromString,
                    response_serializer=coresrv__pb2.SearchGameSalesByNameReply.SerializeToString,
            ),
            'GetTopNGamesOfPlatforms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopNGamesOfPlatforms,
                    request_deserializer=coresrv__pb2.GetTopNGamesOfPlatformsRequest.FromString,
                    response_serializer=coresrv__pb2.GetTopNGamesOfPlatformsReply.SerializeToString,
            ),
            'GetTopNGamesOfYear': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopNGamesOfYear,
                    request_deserializer=coresrv__pb2.GetTopNGamesOfYearRequest.FromString,
                    response_serializer=coresrv__pb2.GetTopNGamesOfYearReply.SerializeToString,
            ),
            'GetTopNGamesOfGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopNGamesOfGenre,
                    request_deserializer=coresrv__pb2.GetTopNGamesOfGenreRequest.FromString,
                    response_serializer=coresrv__pb2.GetTopNGamesOfGenreReply.SerializeToString,
            ),
            'Get5MostSoldGamesByYearAndPlatform': grpc.unary_unary_rpc_method_handler(
                    servicer.Get5MostSoldGamesByYearAndPlatform,
                    request_deserializer=coresrv__pb2.Get5MostSoldGamesByYearAndPlatformRequest.FromString,
                    response_serializer=coresrv__pb2.Get5MostSoldGamesByYearAndPlatformReply.SerializeToString,
            ),
            'GetGameSalesWithMoreSalesInEUThanNA': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameSalesWithMoreSalesInEUThanNA,
                    request_deserializer=coresrv__pb2.GetGameSalesWithMoreSalesInEUThanNARequest.FromString,
                    response_serializer=coresrv__pb2.GetGameSalesWithMoreSalesInEUThanNAReply.SerializeToString,
            ),
            'GetGameSalesInIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameSalesInIds,
                    request_deserializer=coresrv__pb2.GetGameSalesInIdsRequest.FromString,
                    response_serializer=coresrv__pb2.GetGameSalesInIdsReply.SerializeToString,
            ),
            'GetYearlyTotalGameSalesInRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetYearlyTotalGameSalesInRange,
                    request_deserializer=coresrv__pb2.GetYearlyTotalGameSalesInRangeRequest.FromString,
                    response_serializer=coresrv__pb2.GetYearlyTotalGameSalesInRangeReply.SerializeToString,
            ),
            'GetTotalPublishersGameSalesInYearsRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalPublishersGameSalesInYearsRange,
                    request_deserializer=coresrv__pb2.GetTotalPublishersGameSalesInYearsRangeRequest.FromString,
                    response_serializer=coresrv__pb2.GetTotalPublishersGameSalesInYearsRangeReply.SerializeToString,
            ),
            'GetTotalGameSalesInYearsRangeByGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalGameSalesInYearsRangeByGenre,
                    request_deserializer=coresrv__pb2.GetTotalGameSalesInYearsRangeByGenreRequest.FromString,
                    response_serializer=coresrv__pb2.GetTotalGameSalesInYearsRangeByGenreReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coresrv.CoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coresrv.CoreService/Ping',
            coresrv__pb2.PingRequest.SerializeToString,
            coresrv__pb2.PingReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BulkStoreGameSales(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coresrv.CoreService/BulkStoreGameSales',
            coresrv__pb2.BulkStoreGameSalesRequest.SerializeToString,
            coresrv__pb2.BulkStoreGameSalesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGameSalesByRank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coresrv.CoreService/GetGameSalesByRank',
            coresrv__pb2.GetGameSalesByRankRequest.SerializeToString,
            coresrv__pb2.GetGameSalesByRankReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchGameSalesByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coresrv.CoreService/SearchGameSalesByName',
            coresrv__pb2.SearchGameSalesByNameRequest.SerializeToString,
            coresrv__pb2.SearchGameSalesByNameReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTopNGamesOfPlatforms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coresrv.CoreService/GetTopNGamesOfPlatforms',
            coresrv__pb2.GetTopNGamesOfPlatformsRequest.SerializeToString,
            coresrv__pb2.GetTopNGamesOfPlatformsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTopNGamesOfYear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coresrv.CoreService/GetTopNGamesOfYear',
            coresrv__pb2.GetTopNGamesOfYearRequest.SerializeToString,
            coresrv__pb2.GetTopNGamesOfYearReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTopNGamesOfGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coresrv.CoreService/GetTopNGamesOfGenre',
            coresrv__pb2.GetTopNGamesOfGenreRequest.SerializeToString,
            coresrv__pb2.GetTopNGamesOfGenreReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get5MostSoldGamesByYearAndPlatform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coresrv.CoreService/Get5MostSoldGamesByYearAndPlatform',
            coresrv__pb2.Get5MostSoldGamesByYearAndPlatformRequest.SerializeToString,
            coresrv__pb2.Get5MostSoldGamesByYearAndPlatformReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGameSalesWithMoreSalesInEUThanNA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coresrv.CoreService/GetGameSalesWithMoreSalesInEUThanNA',
            coresrv__pb2.GetGameSalesWithMoreSalesInEUThanNARequest.SerializeToString,
            coresrv__pb2.GetGameSalesWithMoreSalesInEUThanNAReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGameSalesInIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coresrv.CoreService/GetGameSalesInIds',
            coresrv__pb2.GetGameSalesInIdsRequest.SerializeToString,
            coresrv__pb2.GetGameSalesInIdsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetYearlyTotalGameSalesInRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coresrv.CoreService/GetYearlyTotalGameSalesInRange',
            coresrv__pb2.GetYearlyTotalGameSalesInRangeRequest.SerializeToString,
            coresrv__pb2.GetYearlyTotalGameSalesInRangeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTotalPublishersGameSalesInYearsRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coresrv.CoreService/GetTotalPublishersGameSalesInYearsRange',
            coresrv__pb2.GetTotalPublishersGameSalesInYearsRangeRequest.SerializeToString,
            coresrv__pb2.GetTotalPublishersGameSalesInYearsRangeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTotalGameSalesInYearsRangeByGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coresrv.CoreService/GetTotalGameSalesInYearsRangeByGenre',
            coresrv__pb2.GetTotalGameSalesInYearsRangeByGenreRequest.SerializeToString,
            coresrv__pb2.GetTotalGameSalesInYearsRangeByGenreReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
